function [scenario, egoVehicle] = paebSceneRHS_Road020()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 08-Jun-2023 10:37:12

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [-119.91220007542 0.28026685394776 0;
    -82.799082818993 -0.8927607107007 0;
    -36.191496881598 -0.19233884199439 0;
    -33.006654412737 0.0042563675231151 0;
    9.6638580024963 0.8130901598853 0;
    37.384414111568 0.15476839718488 0;
    56.296640453451 0.063362891127205 0;
    83.395183268286 0.44487676825404 0;
    108.29658210418 0.17515715843639 0;
    139.47745915091 -0.93972185438385 0];
headings = [-1.81033463389367;-1.81033463389367;3.53229450127628;3.53229450127628;-1.36043338158969;-1.36043338158969;0.806600231691492;0.806600231691492;-2.0477506654296;-2.0477506654296];
marking = [laneMarking('Solid', 'Width', 3)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Dashed', 'Width', 0.125)
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Dashed', 'Width', 0.125)
    laneMarking('Solid', 'Width', 0.125)
    laneMarking('Solid', 'Width', 3)];
lanetypes = [laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')];
laneSpecification = lanespec([3 3], 'Width', [1.34825724463726 3.5 3.5 3.5 3.5 1.48779317020945], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-95.8 -4.9 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'car_004');
waypoints = [-95.8 -4.9 0;
    68.7 -4.3 0];
speed = [17;17];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [-30.6 -5.6 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'Pedestrian');

