function [allData, scenario, sensor] = dsd()
%dsd - Returns sensor detections
%    allData = dsd returns sensor detections in a structure
%    with time for an internally defined scenario and sensor suite.
%
%    [allData, scenario, sensors] = dsd optionally returns
%    the drivingScenario and detection generator objects.

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 19-Jun-2023 16:39:59

% Create the drivingScenario object and ego car
[scenario, egoVehicle] = createDrivingScenario;

% Create all the sensors
sensor = createSensor(scenario);

allData = struct('Time', {}, 'ActorPoses', {}, 'ObjectDetections', {}, 'LaneDetections', {}, 'PointClouds', {}, 'INSMeasurements', {});
running = true;
while running

    % Generate the target poses of all actors relative to the ego vehicle
    poses = targetPoses(egoVehicle);
    time  = scenario.SimulationTime;

    % Generate detections for the sensor
    laneDetections = [];
    ptClouds = [];
    insMeas = [];
    [objectDetections, isValidTime] = sensor(poses, time);
    numObjects = length(objectDetections);
    objectDetections = objectDetections(1:numObjects);

    % Aggregate all detections into a structure for later use
    if isValidTime
        allData(end + 1) = struct( ...
            'Time',       scenario.SimulationTime, ...
            'ActorPoses', actorPoses(scenario), ...
            'ObjectDetections', {objectDetections}, ...
            'LaneDetections', {laneDetections}, ...
            'PointClouds',   {ptClouds}, ... %#ok<AGROW>
            'INSMeasurements',   {insMeas}); %#ok<AGROW>
    end

    % Advance the scenario one time step and exit the loop if the scenario is complete
    running = advance(scenario);
end

% Restart the driving scenario to return the actors to their initial positions.
restart(scenario);

% Release the sensor object so it can be used again.
release(sensor);

%%%%%%%%%%%%%%%%%%%%
% Helper functions %
%%%%%%%%%%%%%%%%%%%%

% Units used in createSensors and createDrivingScenario
% Distance/Position - meters
% Speed             - meters/second
% Angles            - degrees
% RCS Pattern       - dBsm

function sensor = createSensor(scenario)
% createSensors Returns all sensor objects to generate detections

% Assign into each sensor the physical and radar profiles for all actors
profiles = actorProfiles(scenario);
sensor = visionDetectionGenerator('SensorIndex', 1, ...
    'UpdateInterval', 0.3, ...
    'SensorLocation', [1.9 0], ...
    'DetectorOutput', 'Objects only', ...
    'Intrinsics', cameraIntrinsics([800 800],[320 240],[480 640]), ...
    'ActorProfiles', profiles);

function [scenario, egoVehicle] = createDrivingScenario
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Construct a drivingScenario object.
scenario = ia_drivingScenario('GeographicReference', [1e-05 0 0]);

% Add all road segments
roadCenters = [402.55999755859 -202.84999084473 0;
    401.70739915328 -102.2898295253 0;
    400.85480074796 -1.7296682058796 0];
headings = [90.4857701014249;90.4857701014249;90.4857701014249];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [400.7005590875 16.462444471971 0;
    399.97027466094 102.59622009975 0;
    399.23999023437 188.72999572754 0];
headings = [90.4857701014249;90.4857701014249;90.4857701014249];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [987.94000244141 6.0899996757507 0;
    737.94059312886 6.6334547151278 0;
    698.90701743211 6.7183068892815 0;
    487.94118381632 7.1769097545049 0;
    409.87403242282 7.3466141028122 0];
headings = [179.87544918146;179.87544918146;179.87544918146;179.87544918146;179.87544918146];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [391.68133343532 7.3861618520322 0;
    196.4032436514 7.8106623029125 0;
    141.68192412278 7.9296168914092 0;
    1.1251538674754 8.2351627537929 0];
headings = [179.87544918146;179.87544918146;179.87544918146;179.87544918146];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [-16.944052706608 8.274442052081 0;
    -61.663813834 8.3716549999485 0;
    -106.38357496139 8.4688679478161 0];
headings = [179.87544918146;179.87544918146;179.87544918146];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [-124.39222794622 8.5080156131802 0;
    -311.15610542819 8.9140076540026 0;
    -374.39163725877 9.0514706525573 0;
    -497.91998291016 9.3199996948249 0];
headings = [179.87544918146;179.87544918146;179.87544918146;179.87544918146];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [-1.8899999856949 1009.2099609375 0;
    -3.3933991105564 759.21448139623 0;
    -4.8725593289585 513.24961285085 0;
    -4.8967982354179 509.21900185495 0;
    -6.4001973602794 259.22352231368 0;
    -7.855118672222 17.289264764194 0];
headings = [-90.344555775849;-90.344555775849;-90.344555775849;-90.344555775849;-90.344555775849;-90.344555775849];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [-7.963779854157 -0.77965907387306 0;
    -9.4671789790185 -250.77513861515 0;
    -10.051889621903 -348.00481977131 0;
    -10.97057810388 -500.77061815642 0;
    -12.139999389649 -695.22998046875 0];
headings = [-90.344555775849;-90.344555775849;-90.344555775849;-90.344555775849;-90.344555775849];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

roadCenters = [-117.39999389648 87.75 0;
    -116.3882107223 52.759062633167 0;
    -115.37642754811 17.768125266334 0];
headings = [-88.34372093382;-88.34372093382;-88.34372093382];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')
    laneType('Driving')
    laneType('Shoulder')
    laneType('Border')
    laneType('Border')];
laneSpecification = lanespec([4 4], 'Width', [2 0.635 0.5 3.5 3.5 0.5 0.635 2], 'Marking', marking, 'Type', lanetypes);
road(scenario, roadCenters, 'Heading', headings, 'Lanes', laneSpecification, 'Name', 'road_Crossing');

rg = driving.scenario.RoadGroup('Name', 'Roadgroup');
Centers = [-120.691705926437 17.6144307288268 0;
    -121.734119303166 14.939166305525 0;
    -124.380515632524 13.8255003544755 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [0.635 2], 'Marking', marking, 'Type', lanetypes);
headings = [-88.3437209338201;-134.232903401852;-180.122085869884];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-113.627158686468 17.8187063863194 0;
    -113.535878049252 14.66190842691 0;
    -113.533713546524 14.587052488091 0;
    -115.689692128855 9.05409695397244 0;
    -121.163040518503 6.75099178904924 0;
    -124.3960321315 6.75801974799194 0];
marking = [laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [-88.34372093382;271.65627906618;271.65627906618;225.76584689742;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-117.125696409747 17.7175441463494 0;
    -117.122405446408 17.603731330532 0;
    -124.274563644043 10.2577639663655 0;
    -124.388052058222 10.2580106703507 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [-88.3437209338201;-88.3437209338201;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-110.06114916424 17.9218196123459 0;
    -110.044969531712 17.3622724338506 0;
    -108.932894852418 14.8303531781671 0;
    -106.372016530955 13.7863553857591 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [2 0.635], 'Marking', marking, 'Type', lanetypes);
headings = [-88.34372093382;271.658396730921;315.765880470349;359.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-106.379770776117 10.2188638130034 0;
    -106.572747749169 10.2192833112285 0;
    -113.605405292632 17.0663993103904 0;
    -113.610983015198 17.259296114714 0;
    -113.627158686468 17.8187063863194 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [539.87544918146;179.87544918146;451.65627906618;91.65627906618;91.65627906618];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-117.125696409747 17.7175441463494 0;
    -117.030507401878 14.4255813055688 0;
    -114.637828662818 8.97399489457844 0;
    -109.124734375749 6.72482261466266 0;
    -108.989268045606 6.72452813452823 0;
    -106.387379146669 6.71887208262829 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [-88.34372093382;-88.3437209338202;-44.2633355868276;-0.124550818539812;359.87544918146;359.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-106.379227321078 10.4688632223164 0;
    -108.981116220015 10.4745192742164 0;
    -121.230021015852 10.5011462532819 0;
    -124.38788030591 10.5080108876806 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Driving')
    laneType('Shoulder')];
laneSpecification = lanespec(2, 'Width', [3.5 0.5], 'Marking', marking, 'Type', lanetypes);
headings = [539.87544918146;539.87544918146;539.87544918146;539.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-106.390786609765 5.15137578623865 0;
    -108.992675508703 5.15703183813859 0;
    -121.241580304539 5.18365881720407 0;
    -124.399439594597 5.19052345160279 0];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
lanetypes = [laneType('Border')
    laneType('Border')
    laneType('Shoulder')
    laneType('Driving')];
laneSpecification = lanespec(4, 'Width', [2 0.635 0.5 3.5], 'Marking', marking, 'Type', lanetypes);
headings = [539.87544918146;539.87544918146;539.87544918146;539.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

roadGroup(scenario, rg);

rg = driving.scenario.RoadGroup('Name', 'Roadgroup1');
Centers = [1.13671315616309 13.5526501898702 0;
    -1.4698401190406 14.6419026465909 0;
    -2.53771569898984 17.257141213023 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [0.635 2], 'Marking', marking, 'Type', lanetypes);
headings = [179.87544918146;134.765434541813;89.6577197861314];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [1.12895805275119 9.98515861898026 0;
    0.979445304934753 9.98548363357319 0;
    -6.10604942689434 17.1292305727126 0;
    -6.1051524293881 17.2783894474318 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [179.87544918146;179.87544918146;89.6554442241511;89.6554442241511];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-9.60508702901096 17.2997885580677 0;
    -9.60550267188008 17.2306726216099 0;
    -9.61898508896203 14.9887241808801 0;
    -9.61909353567534 14.9706909203413 0;
    -9.61976086794669 14.8597223502326 0;
    -7.2071485707281 8.9511626691148 0;
    -1.31849196887457 6.49047067809842 0;
    -1.20752165441005 6.49022944802243 0;
    -1.18995943146379 6.49019127081797 0;
    1.05223328445618 6.48531713557873 0;
    1.12134968219979 6.4851668886051 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [269.655444224151;269.655444224151;269.655444224151;269.655444224151;269.655444224151;314.767393122425;359.87544918146;359.87544918146;359.87544918146;359.87544918146;359.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [1.12080622716042 6.23516747929256 0;
    -7.9137970598812 6.2548071284366 0;
    -16.9484003469228 6.27444677758064 0];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
lanetypes = [laneType('Shoulder')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Width', [0.5 3.5], 'Marking', marking, 'Type', lanetypes);
headings = [179.87544918146;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [1.12950150779045 10.2351580282932 0;
    -7.90510177925117 10.2547976774373 0;
    -16.9397050662928 10.2744373265813 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Driving')
    laneType('Shoulder')];
laneSpecification = lanespec(2, 'Width', [3.5 0.5], 'Marking', marking, 'Type', lanetypes);
headings = [179.87544918146;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [1.12895805275107 9.9851586189807 0;
    -1.2905830227367 9.99041827856933 0;
    -7.02099154330303 7.95359470113549 0;
    -9.6949408794932 2.35827630860359 0;
    -9.69559174437784 2.25004604809027 0;
    -9.71374821094587 -0.769135279999005 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [179.87544918146;179.87544918146;-140.740826158105;-90.344555775849;-90.344555775849;-90.344555775849];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [1.12134968219979 6.4851668886051 0;
    1.05188730324395 6.485317887681 0;
    0.892946008745699 6.48566339828719 0;
    -4.11535840346978 4.42951977767987 0;
    -6.21243796330573 -0.561782238213248 0;
    -6.21381149736798 -0.790182867746809 0];
marking = [laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [179.87544918146;179.87544918146;179.87544918146;224.765445666312;269.655444224151;269.655444224151];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [1.11359457878788 2.91767531771512 0;
    1.04433405643733 2.91782587516965 0;
    -1.55676614389264 1.84989290282292 0;
    -2.64596036191869 -0.742520515579887 0;
    -2.64637600431406 -0.811636373258923 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [2 0.635], 'Marking', marking, 'Type', lanetypes);
headings = [179.87544918146;179.877691612017;224.765444870265;-90.344555775849;-90.344555775849];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-6.10515031543313 17.2787409703197 0;
    -6.11904987480486 14.9674272592095 0;
    -6.11969923457328 14.8594472796987 0;
    -8.20331944178682 9.14581346595019 0;
    -13.8203982207135 6.5176476381283 0;
    -16.9478568918833 6.52444618689273 0];
marking = [laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [-90.344555775849;269.655444224151;269.655444224151;230.273244785586;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-9.60508702901096 17.2997885580677 0;
    -9.60646056361867 17.0713878378225 0;
    -16.7118450655135 10.0239414080589 0;
    -16.8711323531579 10.0242876707942 0;
    -16.9402485213322 10.0244379172688 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [-90.344555775849;-90.344555775849;179.87544918146;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-13.1725225220649 17.3212420635795 0;
    -13.172938164934 17.252126127122 0;
    -14.2621327161922 14.659712050397 0;
    -16.863377249746 13.5917792416842 0;
    -16.9324934179203 13.5919294881588 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [0.635 2], 'Marking', marking, 'Type', lanetypes);
headings = [-90.344555775849;-90.344555775849;-135.234552493115;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-5.85515483589185 17.2772375711948 0;
    -5.90948542685931 8.24277565216142 0;
    -5.96381601782676 -0.791686266871987 0];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
lanetypes = [laneType('Shoulder')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Width', [0.5 3.5], 'Marking', marking, 'Type', lanetypes);
headings = [-90.344555775849;-90.344555775849;-90.344555775849];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-9.85508250855223 17.3012919571926 0;
    -9.90941309951969 8.2668300381592 0;
    -9.96374369048714 -0.767631880874203 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Driving')
    laneType('Shoulder')];
laneSpecification = lanespec(2, 'Width', [3.5 0.5], 'Marking', marking, 'Type', lanetypes);
headings = [-90.344555775849;-90.344555775849;-90.344555775849];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-16.9402485213322 10.0244379172688 0;
    -16.871132353158 10.0242876707942 0;
    -13.9207868119803 10.0178741350311 0;
    -13.8214730256842 10.0176582442105 0;
    -8.41147171925237 7.75687442185182 0;
    -6.19505638884813 2.32854473474608 0;
    -6.21381149736798 -0.790182867746724 0];
marking = [laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [359.87544918146;359.87544918146;359.87544918146;359.87544918146;314.765455654202;269.655444224151;269.655444224151];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-9.71374609699084 -0.768783757121945 0;
    -9.71284909951329 -0.619624887171592 0;
    -16.798344148847 6.52412117231019 0;
    -16.9478568918833 6.52444618689273 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [89.655444224151;89.6554442241511;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [-16.9556119952952 2.95695461600275 0;
    -14.3490584371472 1.86770235661855 0;
    -13.2811828273892 -0.747535522728048 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [0.635 2], 'Marking', marking, 'Type', lanetypes);
headings = [-0.124550818539812;-45.2345538030071;-90.3422802132152];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

roadGroup(scenario, rg);

rg = driving.scenario.RoadGroup('Name', 'Roadgroup2');
Centers = [402.604737852147 -1.7148313801938 0;
    402.577883568962 1.45251098447752 0;
    400.293183635964 6.8788137143876 0;
    394.85258730245 9.12927223498472 0;
    394.738677570738 9.12951985484098 0;
    391.6851376206 9.13615771721996 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [90.4857701014249;90.4857701014245;135.180477931467;179.87544918146;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [399.104863643777 -1.74450503156538 0;
    399.103235102202 -1.55242585047975 0;
    399.101814877604 -1.38491672334589 0;
    392.03712654586 5.63538428514691 0;
    391.677529250049 5.6361659868441 0];
marking = [laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [90.4857701014249;90.4857701014248;90.4857701014248;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [406.017867974072 16.5075272265901 0;
    406.019494841817 16.3156457779923 0;
    407.106157789439 13.7348920521212 0;
    409.693840691307 12.6645183721075 0;
    409.885591711503 12.66410153889 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [2 0.635], 'Marking', marking, 'Type', lanetypes);
headings = [270.485770101425;270.487941031224;315.180491249149;359.87544918146;359.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [409.87022823754 5.59661823762443 0;
    409.678480915234 5.59703506280366 0;
    406.816453118588 5.60325661121907 0;
    406.702774849181 5.60350372791644 0;
    398.977476269661 13.2802649084884 0;
    398.976510519292 13.3941708368682 0;
    398.952247634105 16.255869420067 0;
    398.950621983313 16.4476076462847 0];
marking = [laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [539.87544918146;539.87544918146;179.87544918146;179.87544918146;90.4857701014246;450.485770101425;450.485770101425;450.485770101425];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [409.877836608091 9.09660996800003 0;
    409.686089285785 9.097026793179 0;
    409.518233419807 9.09739168250615 0;
    402.453544959108 16.1176928416907 0;
    402.452121842475 16.2855430714386 0;
    402.450496191683 16.4772812976563 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [539.87544918146;539.87544918146;179.87544918146;450.485770101425;450.485770101425;450.485770101425];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [402.450496191683 16.4772812976563 0;
    402.452121842475 16.2855430714386 0;
    402.476386735533 13.4236076689624 0;
    402.477177400649 13.3303522615811 0;
    400.257833792465 7.8829807321348 0;
    394.824564566214 5.62932488187361 0;
    391.677529250049 5.6361659868441 0];
marking = [laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [270.485770101425;270.485770101425;270.485770101425;270.485770101425;225.180742692376;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [395.383250200924 16.417361717351 0;
    394.31300288746 13.7904393856983 0;
    391.693041578657 12.7036489674286 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [0.635 2], 'Marking', marking, 'Type', lanetypes);
headings = [-89.5142298985757;-134.819239672178;-180.122275800041];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [391.685494120762 9.13615694225062 0;
    391.825877826606 9.13585177260002 0;
    398.951815207791 16.3068721660246 0;
    398.950621983313 16.4476076462847 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [359.87544918146;359.87544918146;90.4857701014247;90.4857701014247];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [409.869684782501 5.34661882831189 0;
    400.773335288755 5.36639270292186 0;
    391.67698579501 5.38616657753182 0];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
lanetypes = [laneType('Shoulder')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Width', [0.5 3.5], 'Marking', marking, 'Type', lanetypes);
headings = [179.87544918146;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [409.878380063131 9.34660937731257 0;
    400.782030569385 9.36638325192254 0;
    391.68568107564 9.3861571265325 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Driving')
    laneType('Shoulder')];
laneSpecification = lanespec(2, 'Width', [3.5 0.5], 'Marking', marking, 'Type', lanetypes);
headings = [179.87544918146;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [398.854872628893 -1.74662457809192 0;
    398.777751798661 7.34943176083314 0;
    398.700630968429 16.4454880997582 0];
marking = [laneMarking('Unmarked')
    laneMarking('Unmarked')
    laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)];
lanetypes = [laneType('Shoulder')
    laneType('Driving')];
laneSpecification = lanespec(2, 'Width', [0.5 3.5], 'Marking', marking, 'Type', lanetypes);
headings = [90.4857701014249;90.4857701014249;90.4857701014249];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [402.854728867031 -1.71271183366726 0;
    402.777608036799 7.3833445052578 0;
    402.700487206566 16.4794008441829 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')
    laneMarking('Unmarked')];
lanetypes = [laneType('Driving')
    laneType('Shoulder')];
laneSpecification = lanespec(2, 'Width', [3.5 0.5], 'Marking', marking, 'Type', lanetypes);
headings = [90.4857701014249;90.4857701014249;90.4857701014249];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [409.877836608091 9.09660996800003 0;
    409.686089285785 9.09702679317926 0;
    406.824292972951 9.1032478383893 0;
    406.730797588445 9.10345108102099 0;
    401.297527366415 6.84979586886599 0;
    399.078182437636 1.40242367136887 0;
    399.078975110778 1.30893142623159 0;
    399.103237994215 -1.55276695042234 0;
    399.104863643777 -1.74450503156538 0];
marking = [laneMarking('DoubleSolid', 'Color', [0.98 0.86 0.36], 'Width', 0.125)
    laneMarking('Unmarked')];
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [539.87544918146;539.87544918146;539.87544918146;179.87544918146;225.18072377733;270.485770101425;270.485770101425;270.485770101425;270.485770101425];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [406.172109634536 -1.68458545126005 0;
    409.862326505904 2.02913346651614 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [0.635 2], 'Marking', marking, 'Type', lanetypes);
headings = [90.485770101425;-0.122103677422372];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [402.604737852147 -1.7148313801938 0;
    402.603544627293 -1.57409585566845 0;
    409.729487987268 5.59692418234006 0;
    409.869871737267 5.59661901259349 0];
marking = laneMarking('Unmarked');
laneSpecification = lanespec(1, 'Width', 3.5, 'Marking', marking);
headings = [90.4857701014248;90.4857701014248;-0.124550818539837;-0.124550818539837];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

Centers = [395.537491861388 -1.77475096049913 0;
    395.535864993595 -1.58286950426822 0;
    394.449202255489 0.997884128253082 0;
    391.861519856695 2.06825759427965 0;
    391.669774146637 2.06867441595413 0];
marking = laneMarking('Unmarked');
lanetypes = [laneType('Border')
    laneType('Border')];
laneSpecification = lanespec(2, 'Width', [2 0.635], 'Marking', marking, 'Type', lanetypes);
headings = [90.4857701014249;90.4879343887674;135.18049147204;179.87544918146;179.87544918146];
road(rg, Centers, 'Lanes', laneSpecification, 'Heading', headings);

roadGroup(scenario, rg);

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-93.602113472264 6.51149970192361 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'car_058');
waypoints = [-93.602113472264 6.51149970192361 0;
    -24 7.2 0;
    -17 7.3 0;
    -11.4 4.3 0;
    -9.3 -4.4 0;
    -9 -15.5 0;
    -9.3 -32.7 0;
    -9.4 -44.6 0;
    -8.8 -64.3 0;
    -9.6 -73 0];
speed = [30;30;30;30;30;30;30;30;30;30];
trajectory(egoVehicle, waypoints, speed);

% Add the non-ego actors
pedestrian_001 = actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [-24.9 -9.3 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'pedestrian_001');
waypoints = [-24.9 -9.3 0;
    -21 -5.3 0;
    -17.2 -1.9 0;
    -11 2.3 0;
    -5.7 7.7 0;
    -1.5 13.7 0;
    4.2 19.9 0];
speed = [1.5;1.5;1.5;1.5;1.5;1.5;1.5];
trajectory(pedestrian_001, waypoints, speed);

truck_001 = vehicle(scenario, ...
    'ClassID', 2, ...
    'Length', 8.2, ...
    'Width', 2.5, ...
    'Height', 3.5, ...
    'Position', [-8.7 120.2 0], ...
    'Mesh', driving.scenario.truckMesh, ...
    'Name', 'truck_001');
waypoints = [-8.7 120.2 0;
    -10.7 -122 0];
speed = [30;30];
trajectory(truck_001, waypoints, speed);

deer_001 = actor(scenario, ...
    'ClassID', 3, ...
    'Length', 1.7, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [-76.6 4.1 0], ...
    'Mesh', driving.scenario.bicycleMesh, ...
    'Name', 'deer_001');
waypoints = [-76.6 4.1 0;
    -33 3.7 0];
speed = [5;5];
trajectory(deer_001, waypoints, speed);

actor(scenario, ...
    'ClassID', 4, ...
    'Length', 0.24, ...
    'Width', 0.45, ...
    'Height', 1.7, ...
    'Position', [-24 14.7 0], ...
    'RCSPattern', [-8 -8;-8 -8], ...
    'Mesh', driving.scenario.pedestrianMesh, ...
    'Name', 'pedestrian_002');

